baseurl = "https://u10.github.io/"
languageCode = "en-us"
title = "u10"
theme = "hyde"

[[menu.main]]
	name = "hugo-helper"
    url = "/projects/hugo-helper"
[[menu.main]]
	name = "rpc4js"
    url = "/projects/rpc4js"
    
[Params]
	themeColor = "theme-base-0d"
	description = "by vaniship"
	copyright = "© 2016 by vaniship"


